version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:5000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
